settings:
  logLevel: Info
  comparePairwise: False
  normaliseImages: True
  includeStandoff: True
repoRoot: "../.."
relPaths:
  - division: "Abstract"
    divisionId: "a"
    process: True
    model: "input/abstract/edition.yaml"
    images:
      - "input/abstract/witness_A.yaml"
      - "input/abstract/witness_B.yaml"
    normRules: "hkoll/NormalisationRules.json"
    standoff:
      - "input/abstract/standoff.yaml"
    output: "output/abstract.xml"
    logFile: "output/abstract_log.txt"
  - division: "Catull, Carmina"
    divisionId: "cat"
    process: True
    model: "input/catull/catull_edition.yaml"
    images:
      - "input/catull/catull_G.yaml"
      - "input/catull/catull_m.yaml"
      - "input/catull/catull_O.yaml"
      - "input/catull/catull_R.yaml"
    standoff: []
    output: "output/catull.xml"
    logFile: "output/catull_log.txt"
  - division: "Dante, Commedia"
    divisionId: "com"
    process: True
    model: "input/dante/dante_ed_Petrocchi.yaml"
    images:
      - "input/dante/dante_Ash.yaml"
      - "input/dante/dante_Ham.yaml"
      - "input/dante/dante_LauSC.yaml"
    normRules: "input/dante/dante_NormRules.json"
    standoff: []
    output: "output/dante.xml"
    logFile: "output/dante_log.txt"
