settings:
  logLevel: Info
  comparePairwise: False
  normaliseImages: True
  includeStandoff: True
repoRoot: "../.."
relPaths:
  - division: "Abstract"
    divisionId: "a"
    process: True
    model: "input/abstract/edition.yaml"
    images:
      - "input/abstract/witness_A.yaml"
      - "input/abstract/witness_B.yaml"
    normRules: "hkoll/NormalisationRules.json"
    standoff:
      - "input/abstract/standoff.yaml"
    output: "output/abstract.xml"
    logFile: "output/abstract_log.txt"
  - division: "Catullus, Carmina"
    divisionId: "cat"
    process: True
    model: "input/catullus/catullus_edition.yaml"
    images:
      - "input/catullus/catullus_G.yaml"
      - "input/catullus/catullus_m.yaml"
      - "input/catullus/catullus_O.yaml"
      - "input/catullus/catullus_R.yaml"
    standoff: []
    output: "output/catullus.xml"
    logFile: "output/catullus_log.txt"
  - division: "Dante, Commedia"
    divisionId: "com"
    process: True
    model: "input/dante/dante_ed_Petrocchi.yaml"
    images:
      - "input/dante/dante_Ash.yaml"
      - "input/dante/dante_Ham.yaml"
      - "input/dante/dante_LauSC.yaml"
    normRules: "input/dante/dante_NormRules.json"
    standoff: []
    output: "output/dante.xml"
    logFile: "output/dante_log.txt"
